'use client';

import { BlogPost } from '@/data/blogPosts';
import SafeImage from './SafeImage';

interface PostCardProps {
  post: BlogPost;
  locale: string;
}

export default function PostCard({ post, locale }: PostCardProps) {
  const postUrl = `/${locale}/posts/${post.slug}`;
  
  // Listas COMPLETAS de imágenes verificadas que realmente existen
  const categoryImages: Record<string, string[]> = {
    'cancun': [
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_01.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_02.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_03.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_04.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_05.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_06.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_07.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_08.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_09.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_10.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_11.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_12.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_13.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_14.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_15.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_16.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_17.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_18.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_19.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_20.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_21.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_22.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_23.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_24.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_25.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_26.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_27.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_28.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_29.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_30.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_31.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_32.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_33.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_34.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_35.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_36.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_37.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_38.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_39.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_40.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_41.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_42.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_43.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_44.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_45.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_46.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_47.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_48.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_49.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_50.jpg',
      '/assets/PoolFotos/CUN/VAQUITA/MT_Vaquita_Cancun_01.jpg',
      '/assets/PoolFotos/CUN/VAQUITA/MT_Vaquita_Cancun_02.jpg',
      '/assets/PoolFotos/CUN/VAQUITA/MT_Vaquita_Cancun_03.jpg',
      '/assets/PoolFotos/CUN/VAQUITA/MT_Vaquita_Cancun_04.jpg',
      '/assets/PoolFotos/CUN/VAQUITA/MT_Vaquita_Cancun_05.jpg',
      '/assets/PoolFotos/CUN/RAKATA/RAKATA_CUN_FOTOGRAFIA_1.jpg',
      '/assets/PoolFotos/CUN/RAKATA/RAKATA_CUN_FOTOGRAFIA_2.jpg',
      '/assets/PoolFotos/CUN/RAKATA/RAKATA_CUN_FOTOGRAFIA_3.jpg',
      '/assets/PoolFotos/CUN/RAKATA/RAKATA_CUN_FOTOGRAFIA_4.jpg',
      '/assets/PoolFotos/CUN/RAKATA/RAKATA_CUN_FOTOGRAFIA_5.jpg',
      '/assets/PoolFotos/CUN/HOF/HOF_CUN_MT_Fotos1500x1000_1_V01.jpg',
      '/assets/PoolFotos/CUN/HOF/HOF_CUN_MT_Fotos1500x1000_2_V01.jpg',
      '/assets/PoolFotos/CUN/HOF/HOF_CUN_MT_Fotos1500x1000_3_V01.jpg',
      '/assets/PoolFotos/CUN/HOF/HOF_CUN_MT_Fotos1500x1000_4_V01.jpg',
    ],
    'tulum': [
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_01.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_02.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_03.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_04.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_05.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_06.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_07.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_08.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_09.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_10.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_11.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_12.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_13.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_14.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_15.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_16.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_17.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_18.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_19.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_20.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_01.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_02.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_03.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_04.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_05.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_06.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_07.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_08.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_09.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_10.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_11.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_12.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_13.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_14.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_15.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_16.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_17.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_18.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_19.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_20.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_21.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_22.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_23.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_24.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_25.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_26.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_27.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_28.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_29.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_30.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_31.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_32.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_33.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_34.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_35.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_36.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_37.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_38.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_39.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_40.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_41.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_42.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_43.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_44.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_45.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_46.jpg',
      '/assets/PoolFotos/TULUM/TEHMPLO/MT_Themplo_47.jpg',
      '/assets/PoolFotos/TULUM/VAGALUME/MT_Vagalume_1.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_1.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_3.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_5.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_7.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_9.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_13.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_14.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_17.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_19.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_20.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_21.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_22.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_23.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_24.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_25.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_26.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_27.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_29.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_30.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_31.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_32.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_33.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_34.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_35.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_36.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_37.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_38.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_39.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_40.jpg',
      '/assets/PoolFotos/TULUM/BAGATELLE/Pic_41.jpg',
    ],
    'playa-del-carmen': [
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_1.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_2.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_3.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_4.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_5.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_6.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_7.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_8.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_9.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_10.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_11.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_12.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_13.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_14.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_15.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_16.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_17.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_18.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_19.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_20.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_21.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_22.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_23.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_24.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_25.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_26.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_27.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_28.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_29.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_30.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_31.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_32.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_33.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_34.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_35.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_36.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_37.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_38.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_39.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_40.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_41.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_42.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_43.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_44.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_45.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_46.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_47.jpg',
      '/assets/PoolFotos/PDC/VAQUITA/MT_Vaquita_PDC_1.jpg',
      '/assets/PoolFotos/PDC/SANTITO/MT_SANTITO_01.png',
    ],
    'los-cabos': [
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_1_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_2_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_3_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_4_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_5_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_6_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_7_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_8_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_9_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_10_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_11_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_12_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_13_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_14_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_15_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_16_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_17_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_18_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_19_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_20_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_21_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_22_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_23_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_24_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_25_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_26_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_27_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_28_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_29_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_30_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_31_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_32_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_33_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_34_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_35_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_36_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_37_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_38_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_39_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_40_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_41_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_42_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_43_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_44_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_45_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_46_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_47_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_48_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_49_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_50_V01.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_51_V01.jpg',
      '/assets/PoolFotos/CSL/VAQUITAA/LaVaquita_CSL_MandalaTickets_2025_NOV_Fotos_V01_U01.jpg',
      '/assets/PoolFotos/CSL/VAQUITAA/LaVaquita_CSL_MandalaTickets_2025_NOV_Fotos_V01_U02.jpg',
      '/assets/PoolFotos/CSL/VAQUITAA/LaVaquita_CSL_MandalaTickets_2025_NOV_Fotos_V01_U03.jpg',
    ],
    'puerto-vallarta': [
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_1.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_2.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_3.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_4.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_5.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_6.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_7.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_8.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_9.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_10.jpg',
      '/assets/PoolFotos/VTA/VAQUITA/V1.jpg',
      '/assets/PoolFotos/VTA/VAQUITA/V2.jpg',
      '/assets/PoolFotos/VTA/VAQUITA/V3.jpg',
      '/assets/PoolFotos/VTA/VAQUITA/V4.jpg',
      '/assets/PoolFotos/VTA/VAQUITA/V5.jpg',
      '/assets/PoolFotos/VTA/RAKATA/MT_Rakata_VTA_1.jpg',
    ],
    'general': [
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_01.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_02.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_03.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_04.jpg',
      '/assets/PoolFotos/CUN/MANDALA/MT_Mandala_Cancun_05.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_01.jpg',
      '/assets/PoolFotos/TULUM/BONBONNIERE/MT_Bonbinniere_02.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_1.jpg',
      '/assets/PoolFotos/PDC/MANDALA/MT_Mandala_PDC_2.jpg',
      '/assets/PoolFotos/CSL/MANDALA/Mandala_CSL_MT_Fotos1500x1000_1_V01.jpg',
      '/assets/PoolFotos/VTA/MANDALA/MT_Mandala_Vta_1.jpg',
    ],
  };

  // Función hash simple para mejor distribución
  const hashPostId = (id: string): number => {
    let hash = 0;
    for (let i = 0; i < id.length; i++) {
      const char = id.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash; // Convert to 32bit integer
    }
    return Math.abs(hash);
  };

  // Obtener lista de imágenes disponibles para esta categoría
  const imageList = categoryImages[post.category] || categoryImages['general'];
  
  // Usar hash determinístico basado en el ID del post
  const postIdNum = parseInt(post.id) || 1;
  const hash = hashPostId(post.id);
  const imageIndex = hash % imageList.length;
  const imageUrl = imageList[imageIndex] || imageList[0];
  // Usar ruta absoluta desde la raíz - Next.js servirá desde public/ automáticamente
  // El rewrite de Vercel manejará /blog/assets/ -> /assets/
  const finalImageUrl = imageUrl.startsWith('/') ? imageUrl : `/${imageUrl}`;

  return (
    <article className="post-card">
      <a href={postUrl} className="post-card-link">
        <div className="post-card-image-wrapper">
          <SafeImage
            src={finalImageUrl}
            alt={post.title}
            className="post-card-image"
            loading="lazy"
          />
        </div>
        <div className="post-card-content">
          <h2 className="post-card-title">{post.title}</h2>
          <p className="post-card-excerpt">{post.excerpt}</p>
          <div className="post-card-meta">
            <span className="post-card-category">{post.category}</span>
            <span className="post-card-date">{new Date(post.date).toLocaleDateString(locale)}</span>
          </div>
        </div>
      </a>
    </article>
  );
}
